function AlphabetPreferences(AlphabetWinHandle)
%Sets the modes for alphabet transmission.

%% Initialize the user variables ----------------------------------
% Get all the variables from the PreferencesFile.mat
% This loads the variable arrays allUsersPrefs and windowsPrefs
    load('ProgramData/PreferencesFile.mat', 'allUsersPrefs',...
        'windowsPrefs', 'glob');

% Setup Current User data
    activeUserIndex = glob.selectedUserIndex;
    userName = glob.selectedUserName;

% Get the alpha preferences from the user file
    alphaPrefs = allUsersPrefs{5, activeUserIndex};
    
% Initilize some variables and set defaults
    alphaSelect = alphaPrefs.include;  %1 = Alphabet = 26,
        % +Numbers = 36,+Puncuation = 53, +Special Characters = 59
    sequentialSelect = alphaPrefs.format;   % 1 = continuous ; 2 = random
    groupSelect = alphaPrefs.group;         % 1 = no group ; 2 = groups
    groupMin = alphaPrefs.min;              % random group minimum size
    groupMax = alphaPrefs.max;              % random group maximum size
    
    if groupSelect == 1 % No groups
        enableAction = 'off';
        minDisplay = '-';
        maxDisplay = '-';
    else                % Groups
        enableAction = 'on';
        minDisplay = num2str(alphaPrefs.min);
        maxDisplay = num2str(alphaPrefs.max);
    end
    
    alphaGroups{1} = '  Alphabet Only';
    alphaGroups{2} = '  Alpha + Numbers';
    alphaGroups{3} = '  Alpha + Num + Puncuation';
    alphaGroups{4} = '  Alpha + Num + Puncuation + Special'; 
    
%% Set up main user interface  ------------------------------------
% Initialize figure variables

    windowWidth = windowsPrefs{5,7};
    windowHeight =  windowsPrefs{6,7};
    textFont = windowsPrefs{7,7};

%   Create the new figure
    figure(...
        'CloseRequestFcn',@CloseWindow,...
        'Units', 'characters',...
        'Position',[windowsPrefs{3,7},windowsPrefs{4,7},...
            windowWidth,windowHeight],...
        'NumberTitle', 'off','MenuBar', 'none','Resize', 'off',...
        'DockControls', 'off','Toolbar', 'none',...
        'Color', glob.figureColor ,...
        'Name', 'Alphabet Preferences'...
    );

%   Set up Application title
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .89 1 .1 ],...
        'FontSize', textFont+2,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string','Alphabet Preferences Management'...
    ); 

% Create uicontrol to display Current Selected User Name
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .76 1 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', ['Current Selected User:  ' userName]...
    ); 

% Create drop down box to select alphabet content
    uicontrol('Style', 'popup',...
        'Units', 'normalized',...
        'Position', [ .1 .64 .8 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', alphaGroups,...
        'value' , alphaSelect,...
        'callback', {@UpdateAlphaCallback, 0 } ...
    );

% Create drop down box to select Sequential or Random
    uicontrol('Style', 'popup',...
        'Units', 'normalized',...
        'Position', [ .3 .5 .4 .08 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'HorizontalAlignment','center',...
        'BackgroundColor',glob.figureColor,...
        'string', {'  Sequential' '  Random'},...
        'value' , sequentialSelect,...
        'callback', {@UpdateAlphaCallback, 2 } ...
    );

% Create drop down box to select Groups or No Groups
    uicontrol('Style', 'popup',...
        'Units', 'normalized',...
        'Position', [ .1 .33 .3 .08 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', {'  No Groups' '  Groups'},....
        'value' , groupSelect,...
        'callback', {@UpdateAlphaCallback, 3 } ...
    );

% Create label for minimum group size
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ .43 .30 .1 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', 'Min:'...
    );

% Create edit box to enter minimum group size
    MinHan = uicontrol('Style', 'edit',...
        'Units', 'normalized',...
        'Position', [ .53 .30 .1 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.boxColor,...
        'HorizontalAlignment','center',...
        'Enable', enableAction ,...
        'string', minDisplay,...
        'callback', {@UpdateAlphaCallback, 4 }...
    );

% Create label for maximum group size
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ .67 .30 .1 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', 'Max:'...
    ); 

% Create edit box to enter maximum group size
    MaxHan = uicontrol('Style', 'edit',...
        'Units', 'normalized',...
        'Position', [ .78 .30 .1 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.boxColor,...
        'HorizontalAlignment','center',...
        'Enable', enableAction ,...
        'string', maxDisplay,...
        'callback', {@UpdateAlphaCallback, 5 } ...
    );

%% Action pushbuttons ---------------------------------------------
% Create pushbutton to save selections
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.13 .07 .3 .16 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'ForegroundColor',glob.foregroundColor,...
        'BackgroundColor',glob.backgroundColor,...
        'HorizontalAlignment','center',...         
        'string', 'Save',...
        'callback', {@UpdateAlphaCallback, 6 } ...
    );
    
% Create pushbutton to exit without saving
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.57 .07 .3 .16 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'ForegroundColor',glob.foregroundColor,...
        'BackgroundColor',glob.backgroundColor,...
        'HorizontalAlignment','center',...
        'string', 'Exit',...
        'callback', {@UpdateAlphaCallback, 7 } ...
    );

%% UpdateAlphaCallback --------------------------------------------
    function UpdateAlphaCallback(src, ~, num)
        switch num
            case 0  % Alpha Select Drop Down Menu
                alphaSelect = get(src,'Value');


            case 2  % Sequential/Random Selection
                % 1 = sequential ; 2 = random
                sequentialSelect = get(src,'Value');

            case 3  % Groups or No Groups
                % 1 = no groups ; 2 = groups
                groupSelect = get(src,'Value');
                if groupSelect == 1 % No groups
                    set(MinHan, 'Enable', 'off');
                    set(MaxHan, 'Enable', 'off');
                    set(MinHan, 'String', '-');
                    set(MaxHan, 'String', '-');
                else                % Groups
                    set(MinHan, 'Enable', 'on');
                    set(MaxHan, 'Enable', 'on');
                    set(MinHan, 'String', '5');
                    set(MaxHan, 'String', '5');
                end
                    
                
            case 4  % Group Min size
                groupMin = str2double(get(src,'String'));
                
            case 5  % Group Max size
                groupMax = str2double(get(src,'String'));
                
            case 6  % Save
                alphaPrefs.include = alphaSelect;  
                alphaPrefs.format = sequentialSelect;     
                alphaPrefs.group = groupSelect;
                alphaPrefs.min = groupMin;   
                alphaPrefs.max = groupMax;
                allUsersPrefs{5, activeUserIndex} = alphaPrefs;
                
                % Update the structure allUsersPrefs to include new changes
                save('ProgramData/PreferencesFile.mat',...
                    'allUsersPrefs', 'windowsPrefs', 'glob');              
                delete(gcf)
                delete(AlphabetWinHandle)             
                run('TransmitAlphabet')
                
            case 7  % Exit
                CloseWindow()

        end % end switch
        
    end % end UpdateAlphaCallback
    
end % AlphabetPreferences
