function FlasherPreferences()
% This function is called when the user selects Flasher Preferences on 
% the main figure menu. This window opens and the user can edit Flasher
% Preferences.

%% Initialize the user variables ----------------------------------
% Get all the variables from the PreferencesFile.mat
% This loads the variable arrays allUsersPrefs, windowsPrefs and glob
    load('ProgramData/PreferencesFile.mat', 'allUsersPrefs',...
        'windowsPrefs', 'glob');
  
% Set up some variables
    white = [1  1  1];
    green = [.255 .627 .225];

    windowWidth = windowsPrefs{5,14};
    windowHeight =  windowsPrefs{6,14};
    textFont = windowsPrefs{7,14};
    
%% Create the figure and its contents -----------------------------
% Create the new figure
    figure(...
        'CloseRequestFcn',@CloseRequestCallback,...
        'Units', 'Characters',...
        'Position',[windowsPrefs{3,14},windowsPrefs{4,14},...
            windowWidth,windowHeight],...
        'NumberTitle', 'off', 'Toolbar', 'none', 'Resize', 'off',...  
        'MenuBar', 'none', 'DockControls', 'off', 'Color', white ,...
        'Name', 'Flasher Preferences'...
    );
    
% Set up Application title
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .84 1 .13 ],...
        'FontSize', textFont+1,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string','Flasher Preferences Management'...
        ); 
    
% Create uicontrol checkbox for enabling the Flasher function
    uicontrol('Style', 'checkbox',...
        'Units', 'normalized',...
        'Position', [ .18 .7 .8 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', '  Enable Flasher function',...
        'Style','check','Value',glob.flasherEnabled,...
        'Callback', @FlasherCallback ...
    ); 

% Create uicontrol to display Flasher colors
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .54 1 .12 ],... 
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', 'Flasher colors - Click to change'...
        );

%%  Color pushbuttons --------------------------------------------
% On Color pushbutton
    OnHandle = uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.25 .31 .2 .2 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.flasherOn,'HorizontalAlignment','center',...
        'string', 'On',...
        'callback', {@ChangeColorCallback, 1}...
    );

%  Off Color pushbutton
    OffHandle = uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.5 .31 .2 .2 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.flasherOff,'HorizontalAlignment','center',...
        'string', 'Off',...
        'callback', {@ChangeColorCallback, 2}...
    );
     
%%  Action pushbuttons --------------------------------------------
% Save pushbutton
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.14 .08 .26 .2 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',green,'HorizontalAlignment','center',...
        'string', 'Save',...
        'callback', @saveWinCallback...
    );

%  Exit pushbutton
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.60 .08 .26 .2 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',green,'HorizontalAlignment','center',...
        'string', 'Exit',...
        'callback', @CloseRequestCallback...
    );
     
%% Callbacks ------------------------------------------------------
% saveWinCallback
% Save the updated variables
    function saveWinCallback(~, ~)
        save('ProgramData/PreferencesFile.mat',...
            'allUsersPrefs', 'windowsPrefs', 'glob');
        CloseWindow()
    end

% Save the new colors
    function ChangeColorCallback(~,~,num)
        switch num
            case 1  % On Color
                selectedColor = uisetcolor(glob.flasherOn,...
                    'Select an On Color');
                set(OnHandle, 'BackgroundColor',selectedColor);
                glob.flasherOn = selectedColor;
            case 2  % Off Color
                selectedColor = uisetcolor(glob.flasherOff,...
                    'Select an Off Color');
                set(OffHandle, 'BackgroundColor',selectedColor);
                glob.flasherOff = selectedColor;
        end % switch
        save('ProgramData/PreferencesFile.mat',...
            'allUsersPrefs', 'windowsPrefs', 'glob');
    end

 % FlasherCallback
    function FlasherCallback(src , ~)
        glob.flasherEnabled = get(src,'Value');
    end

 % CloseRequestCallback 
    function CloseRequestCallback(~, ~)
        CloseWindow()
    end

end % end FlasherPreferences