function HelpAndAboutDisplay(val)
% This function displayes the Help or About windows

% Load the preferences file.
    load('ProgramData/PreferencesFile.mat', 'allUsersPrefs', 'windowsPrefs', 'glob');
    
    white = [1  1  1];
    
    switch val
        case 1  % Help              
        %   This opens help in the MatLab browser
            open('MorseHelp/MorseHelp.html');

        % This opens the help in a pdf viewer
        % open('MorseHelp.pdf');                
        % This opens help in the system browser
        % path = cd;
        % str = ['file:///' path '\MorseHelp\MorseHelp.html'];
        % web(str,'-browser');

        case 2  % About
        %   Create the new Aboutfigure           
            windowWidth = windowsPrefs{5,12};
            windowHeight =  windowsPrefs{6,12};
            textFont = windowsPrefs{7,12};

            aboutString = {'Program created by',...
                'James Willmann',...
                'jbw@jwillmann.com',...
                'Version 2.0 - 10/1/2018',...
                'Using MatLab R2018b'};
            figure(...
                'Units', 'Characters',...
                'CloseRequestFcn',@CloseWindow,...
                'Position',[windowsPrefs{3,12}, windowsPrefs{4,12},...
                    windowWidth,windowHeight],...
                'NumberTitle', 'off','MenuBar', 'none','Resize', 'off',...
                'DockControls', 'off','Toolbar', 'none','Color', white,...
                'Name', 'About'...
            );

        %   Set up Application title
            uicontrol('Style', 'text',...
                'Units', 'normalized',...
                'Position', [ 0 .76 1 .2 ],...
                'FontSize', textFont+1,'FontWeight','bold',...
                'BackgroundColor',white,'HorizontalAlignment','center',...
                'string','Morse Code Practice System '...
            ); 

        % Create uicontrol to display message
            uicontrol('Style', 'text',...
                'Units', 'normalized',...
                'Position', [ 0 .1 1 .65 ],...
                'FontSize', textFont,'FontWeight','bold',...
                'BackgroundColor',white,'HorizontalAlignment','center',...
                'string',aboutString ...
            );
        
    end  % end switch 
    
end % end HelpAndAboutDisplay