function ProgramPreferences()
% This function is called when the user selects Window Preferences on 
% the main figure menu. This window opens and the user can edit Window
% Preferences.

%% Initialize the user variables ----------------------------------
% Get all the variables from the PreferencesFile.mat
% This loads the variable arrays allUsersPrefs, windowsPrefs and glob.
    load('ProgramData/PreferencesFile.mat', 'allUsersPrefs',...
        'windowsPrefs', 'glob');
  
% Set up some variables
    white = [1  1  1];
    green = [.255 .627 .225];

    windowWidth = windowsPrefs{5,8};
    windowHeight =  windowsPrefs{6,8};
    textFont = windowsPrefs{7,8};

    displayString = ['Selected User:  ' glob.selectedUserName];
    
%% Create the figure and its contents -----------------------------
% Create the new figure
    figure(...
        'CloseRequestFcn',@CloseRequestCallback,...
        'Units', 'Characters',...
        'Position',[windowsPrefs{3,8},windowsPrefs{4,8},...
            windowWidth,windowHeight],...
        'NumberTitle', 'off', 'Toolbar', 'none', 'Resize', 'off',...  
        'MenuBar', 'none', 'DockControls', 'off', 'Color', white ,...
        'Name', 'Program Preferences'...
    );
    
% Set up Application title
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .85 1 .13 ],...
        'FontSize', textFont+1,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string','Program Preferences Management'...
        ); 
    
% Create uicontrol to display Current Selected User Name
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .77 1 .12 ],... 
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', displayString...
        );
    
% Create uicontrol for checkbox about saving window position on exit
    uicontrol('Style', 'checkbox',...
        'Units', 'normalized',...
        'Position', [ .14 .71 .78 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', '  Save Window Position on exit',...
        'Style','check','Value',glob.saveWindows,...
        'Callback', @CheckBoxCallback ...
    );

% Create uicontrol to display scale factor
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ .17 .60 .5 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', 'Window Scale Factor  '...
        );

    uicontrol('Style', 'edit',...
        'Units', 'normalized',...
        'Position', [ .65 .62 .1 .07 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', num2str(glob.scaleFactor,4),...
        'callback', @ScaleCallback...
    );
    
% Create uicontrol to display volume control
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ .16 .50 .5 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', 'Audio Volume  '...
        );

    uicontrol('Style', 'edit',...
        'Units', 'normalized',...
        'Position', [ .58 .53 .1 .07 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', num2str(glob.scaleFactor,4),...
        'callback', @ScaleCallback...
    );

% Create uicontrol checkbox for enabling the Flasher function
    uicontrol('Style', 'checkbox',...
        'Units', 'normalized',...
        'Position', [ .18 .4 .8 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', '  Enable Flasher function',...
        'Style','check','Value',glob.flasherEnabled,...
        'Callback', @FlasherCallback ...
    ); 

% Create uicontrol to display Flasher colors
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .27 1 .12 ],... 
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', 'Flasher colors - Click to change'...
        );

%%  Color pushbuttons --------------------------------------------
% On Color pushbutton
    OnHandle = uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.31 .21 .15 .08 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.flasherOn,'HorizontalAlignment','center',...
        'string', 'On',...
        'callback', {@ChangeColorCallback, 1}...
    );

%  Off Color pushbutton
    OffHandle = uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.56 .21 .15 .08 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.flasherOff,'HorizontalAlignment','center',...
        'string', 'Off',...
        'callback', {@ChangeColorCallback, 2}...
    );
     
%%  Action pushbuttons --------------------------------------------
% Save pushbutton
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.13 .07 .2 .08 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',green,'HorizontalAlignment','center',...
        'string', 'Save',...
        'callback', @saveWinCallback...
    );

%  Exit pushbutton
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.62 .07 .2 .08 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',green,'HorizontalAlignment','center',...
        'string', 'Exit',...
        'callback', @CloseRequestCallback...
    );

%% Callbacks ------------------------------------------------------
% saveWinCallback
% Save the updated variables
    function saveWinCallback(~,~)
        save('ProgramData/PreferencesFile.mat',...
            'allUsersPrefs', 'windowsPrefs', 'glob');
        CloseWindow()
    end
           
 % CheckBoxCallback
    function CheckBoxCallback(src , ~)
        glob.saveWindows = get(src,'Value');
    end

 % ScaleCallback
    function ScaleCallback(src , ~)
       glob.scaleFactor = str2double(get(src,'String'));
    end

 % CloseRequestCallback 
    function CloseRequestCallback(~, ~)
        CloseWindow()
    end

 % FlasherCallback
    function FlasherCallback(src , ~)
        glob.flasherEnabled = get(src,'Value');
    end

% Save the new colors
    function ChangeColorCallback(~,~,num)
        switch num
            case 1  % On Color
                selectedColor = uisetcolor(glob.flasherOn,...
                    'Select an On Color');
                set(OnHandle, 'BackgroundColor',selectedColor);
                glob.flasherOn = selectedColor;
            case 2  % Off Color
                selectedColor = uisetcolor(glob.flasherOff,...
                    'Select an Off Color');
                set(OffHandle, 'BackgroundColor',selectedColor);
                glob.flasherOff = selectedColor;
        end % switch

    end

end % end ProgramPreferences