function userAction = WarningWindow(windowsPrefs,messageString)
%  This function creates a new warning figure and 
%  returns 1 if the user selects OK, otherwise it returns 0.

% Set up some variables
    windowWidth = windowsPrefs{5,9};
    windowHeight =  windowsPrefs{6,9};
    textFont = windowsPrefs{7,9};

    white = [1  1  1];
    green = [.255 .627 .225];

    userAction = 0;
                
% Create the figure
    WaitFig = figure(...
        'Units', 'Characters',...
        'Position',[windowsPrefs{3,9},windowsPrefs{4,9},...
            windowWidth,windowHeight],...
        'NumberTitle', 'off','MenuBar', 'none','Resize', 'off',...
        'DockControls', 'off','Toolbar', 'none','Color', white,...
        'Name', 'Delete Warning'...
    );

%   Set up Application title
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .87 1 .12 ],...
        'FontSize', textFont+2,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string','Warning'...
    ); 

% uicontrol to display message
     uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .34 1 .5 ],...
        'FontSize', textFont+2,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string',messageString ...
    ); 

%   OK pushbutton
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.13 .1 .3 .2 ],...
        'FontSize', textFont-2,'FontWeight','bold',...
        'ForegroundColor', green,'HorizontalAlignment','center',... 
        'string', 'OK',...
        'callback', {@ActionCallback, 1} ...
    );
    
%   Cancel pushbutton
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.57 .1 .3 .2 ],...
        'FontSize', textFont-2,'FontWeight','bold',...
        'ForegroundColor', green,'HorizontalAlignment','center',... 
        'string', 'Cancel',...
        'callback', {@ActionCallback, 0} ...
    );
    
    uiwait(WaitFig)
        
 % ActionCallback Callback  
    function ActionCallback(~, ~, num)
        switch num
            case 0  % Cancel
                userAction = 0;
            case 1  % OK
                userAction = 1;
        end
        
        uiresume(gcbf)
        close(gcf)
    end % end ActionCallback
                                   
end % end WarningWindow
