function WindowsColors()

%% Initialize the user variables ----------------------------------
% Get all the variables from the PreferencesFile.mat
% This loads the variable arrays allUsersPrefs, windowsPrefs and glob.
    load('ProgramData/PreferencesFile.mat', 'allUsersPrefs',...
        'windowsPrefs', 'glob');
  
% Set up some variables
    windowWidth = windowsPrefs{5,8};
    windowHeight =  windowsPrefs{6,8};
    textFont = windowsPrefs{7,8};
    line = ...
    '-------------------------------------------------------------------';
    displayString = ' Select a box below to change colors ';
    
%% Create the figure and its header -------------------------------
% Create the new figure
    figure(...
        'CloseRequestFcn',@CloseRequestCallback,...
        'Units', 'Characters',...
        'Position',[windowsPrefs{3,8},windowsPrefs{4,8},...
            windowWidth,windowHeight],...
        'NumberTitle', 'off', 'Toolbar', 'none', 'Resize', 'off',...  
        'MenuBar', 'none', 'DockControls', 'off',...
        'Color', glob.figureColor ,...
        'Name', 'Windows Colors'...
    );
    
% Set up Application title
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .85 1 .13 ],...
        'FontSize', textFont+1,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string','Program Preferences Management'...
        ); 
  
% Create uicontrol to display message
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .79 1 .12 ],... 
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', displayString...
        );
    
%% Window Background Color ----------------------------------------
% Draw line
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .80 1 .05 ],...         
        'FontSize', textFont-5,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', line...
        );
         
% Create uicontrol to display figure background color
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ .1 .68 .7 .12 ],... 
        'FontSize', textFont-1,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', 'Window Background  '...
        );
    
% Figure Background Color pushbutton
    FigureColorHandle = uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.7 .74 .10 .06 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', ' ',...
        'callback', {@ChangeColorCallback, 1}...
    );

%% Control Background Color ----------------------------------------
% Draw line
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .68 1 .05 ],...         
        'FontSize', textFont-5,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', line...
        );
         
% Create uicontrol to display control background color
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ .1 .56 .7 .12 ],... 
        'FontSize', textFont-1,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', 'Control Background  '...
        );
    
% Figure Background Color pushbutton
    ControlBackgroundColorHandle = uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.7 .62 .10 .06 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.backgroundColor,...
        'HorizontalAlignment','center',...
        'string', ' ',...
        'callback', {@ChangeColorCallback, 2}...
    );

%% Control Foreground Color ----------------------------------------
% Draw line
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .55 1 .05 ],...         
        'FontSize', textFont-5,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', line...
        );
         
% Create uicontrol to display control foreground color
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ .1 .43 .7 .12 ],... 
        'FontSize', textFont-1,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', 'Control Foreground  '...
        );
    
% Figure Foreground Color pushbutton
    ControlForegroundColorHandle = uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.7 .49 .10 .06 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.foregroundColor,...
        'HorizontalAlignment','center',...
        'string', ' ',...
        'callback', {@ChangeColorCallback, 3}...
    );

%% Textbox Color ----------------------------------------
% Draw line
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .42 1 .05 ],...         
        'FontSize', textFont-5,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', line...
        );
         
% Create uicontrol to display control Textbox color
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ .1 .30 .7 .12 ],... 
        'FontSize', textFont-1,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', 'Textbox Background '...
        );
    
% Textbox Color pushbutton
    ControlTextboxColorHandle = uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.7 .36 .10 .06 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.boxColor,...
        'HorizontalAlignment','center',...
        'string', ' ',...
        'callback', {@ChangeColorCallback, 4}...
    );

%% Transmit Background Color ----------------------------------------
% Draw line
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .28 1 .05 ],...         
        'FontSize', textFont-5,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', line...
        );
         
% Create uicontrol to display Transmit Background color
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ .1 .16 .7 .12 ],... 
        'FontSize', textFont-1,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', 'Transmit Background '...
        );
    
% Textbox Color pushbutton
    TransmitBackgroundColorHandle = uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.7 .22 .10 .06 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',glob.xmitBackgroundColor,...
        'HorizontalAlignment','center',...
        'string', ' ',...
        'callback', {@ChangeColorCallback, 5}...
    );

%% Action pushbuttons ---------------------------------------------
% Draw line
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .14 1 .05 ],...         
        'FontSize', textFont-5,'FontWeight','bold',...
        'BackgroundColor',glob.figureColor,...
        'HorizontalAlignment','center',...
        'string', line...
        );
    
% Save pushbutton
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.18 .05 .2 .08 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'ForegroundColor',glob.foregroundColor,...
        'BackgroundColor',glob.backgroundColor,...
        'HorizontalAlignment','center',...
        'string', 'Save',...
        'callback', @saveWinCallback...
    );

%  Exit pushbutton
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.62 .05 .2 .08 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'ForegroundColor',glob.foregroundColor,...
        'BackgroundColor',glob.backgroundColor,...
        'HorizontalAlignment','center',...
        'string', 'Exit',...
        'callback', @CloseRequestCallback...
    );

%% Callbacks ------------------------------------------------------
% Save the new colors
    function ChangeColorCallback(~,~,num)
        switch num
            case 1  % Window background color
                selectedColor = uisetcolor(glob.figureColor,...
                    'Select a figure backgroun csolor');
                set(FigureColorHandle, 'BackgroundColor',selectedColor);
                glob.figureColor = selectedColor;
            case 2  % Background Color
                selectedColor = uisetcolor(glob.backgroundColor,...
                    'Select an Background Color');
                set(ControlBackgroundColorHandle,...
                'BackgroundColor',selectedColor);
                glob.backgroundColor = selectedColor;
            case 3  % Foreground Color
                selectedColor = uisetcolor(glob.foregroundColor,...
                    'Select an Foreground Color');
                set(ControlForegroundColorHandle,...
                'BackgroundColor',selectedColor);
                glob.foregroundColor = selectedColor;
            case 4  % Textbox Color Color
                selectedColor = uisetcolor(glob.foregroundColor,...
                    'Select an Textbox Color');
                set(ControlTextboxColorHandle,...
                'BackgroundColor',selectedColor);
                glob.boxColor = selectedColor;
            case 5  % Textbox Color Color
                selectedColor = uisetcolor(glob.foregroundColor,...
                    'Select an Transmit Background Color');
                set(TransmitBackgroundColorHandle,...
                'BackgroundColor',selectedColor);
                glob.xmitBackgroundColor = selectedColor;
        end % switch   
    end

% Save the updated variables
    function saveWinCallback(~,~)
        save('ProgramData/PreferencesFile.mat',...
            'allUsersPrefs', 'windowsPrefs', 'glob');
        delete(gcf)
    end
 
 % CloseRequestCallback 
    function CloseRequestCallback(~, ~)
        delete(gcf)
    end

end % end WindowsColors