function WindowPreferences()
% This function is called when the user selects Window Preferences on 
% the main figure menu. This window opens and the user can edit Window
% Preferences.

%% Initialize the user variables ----------------------------------
% Get all the variables from the PreferencesFile.mat
% This loads the variable arrays allUsersPrefs and windowsPrefs
    load('ProgramData/PreferencesFile.mat', 'allUsersPrefs',...
        'windowsPrefs', 'glob');
  
% Set up some variables
    white = [1  1  1];
    green = [.255 .627 .225];

    windowWidth = windowsPrefs{5,8};
    windowHeight =  windowsPrefs{6,8};
    textFont = windowsPrefs{7,8};

    displayString = ['Selected User:  ' glob.selectedUserName];
    
%% Create the figure and its contents -----------------------------
% Create the new figure
    figure(...
        'CloseRequestFcn',@CloseRequestCallback,...
        'Units', 'Characters',...
        'Position',[windowsPrefs{3,8},windowsPrefs{4,8},...
            windowWidth,windowHeight],...
        'NumberTitle', 'off', 'Toolbar', 'none', 'Resize', 'off',...  
        'MenuBar', 'none', 'DockControls', 'off', 'Color', white ,...
        'Name', 'Window Preferences'...
    );
    
% Set up Application title
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .84 1 .13 ],...
        'FontSize', textFont+1,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string','Windows Preferences Management'...
        ); 
    
% Create uicontrol to display Current Selected User Name
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ 0 .70 1 .12 ],... 
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', displayString...
        );
% Create uicontrol for checkbox about saving window position on exit
    uicontrol('Style', 'checkbox',...
        'Units', 'normalized',...
        'Position', [ .15 .54 .8 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', '  Save Window Position on exit',...
        'Style','check','Value',glob.saveWindows,...
        'Callback', @CheckBoxCallback ...
    );
% Create uicontrol to display scale factor
    uicontrol('Style', 'text',...
        'Units', 'normalized',...
        'Position', [ .25 .4 .3 .1 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', 'Scale Factor  '...
        );

    uicontrol('Style', 'edit',...
        'Units', 'normalized',...
        'Position', [ .55 .38 .2 .11 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',white,'HorizontalAlignment','center',...
        'string', num2str(glob.scaleFactor,4),...
        'callback', @ScaleCallback...
    );
    
%%  Action pushbuttons --------------------------------------------
% Save pushbutton
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.13 .1 .3 .2 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',green,'HorizontalAlignment','center',...
        'string', 'Save',...
        'callback', @saveWinCallback...
    );

%  Exit pushbutton
    uicontrol('Style', 'pushbutton',...
        'Units', 'normalized',...
        'Position', [.57 .1 .3 .2 ],...
        'FontSize', textFont,'FontWeight','bold',...
        'BackgroundColor',green,'HorizontalAlignment','center',...
        'string', 'Exit',...
        'callback', @CloseRequestCallback...
    );
     
%% Callbacks ------------------------------------------------------
% saveWinCallback
% Save the updated variables
    function saveWinCallback(~,~)
        save('ProgramData/PreferencesFile.mat',...
            'allUsersPrefs', 'windowsPrefs', 'glob');
        CloseWindow()
    end
           
 % CheckBoxCallback
    function CheckBoxCallback(src , ~)
        glob.saveWindows = get(src,'Value');
    end

 % ScaleCallback
    function ScaleCallback(src , ~)
       glob.scaleFactor = str2double(get(src,'String'));
    end

 % CloseRequestCallback 
    function CloseRequestCallback(~, ~)
        CloseWindow()
    end

end % end WindowPreferences